### PR TITLE
fixed dialog problem + adjusted tests

### LINKED ISSUE #43: Group validation on cancel
When creating a new group and clicking cancel or closing  the window (with and without text in the group textfield), a warning shows "Group name cannot be empty". 

Expected: Either way group window closes immediately without warning.

### PR DESCRIPTION
**Pull request by thisIsTheFoxe**
Closes #43 

ok, @ingokuba?

### CODE REVIEW

File: src/main/java/dhbw/swingchat/components/ChatWindow.java [hunk 1]
```diff
@@ -126,7 +126,11 @@ public void actionPerformed(ActionEvent e)
                     return;
                 }
                 String groupName = showInputDialog("Enter group name");
-                if (groupName == null || groupName.isEmpty()) {
+                
+                if (groupName == null) {    //Cancel / Escape / Close
```
Comment (thisIsTheFoxe) [inline src/main/java/dhbw/swingchat/components/ChatWindow.java]: > user's input, or null meaning the user canceled the input


([docs reference](https://docs.oracle.com/javase/7/docs/api/javax/swing/JOptionPane.html#showInputDialog(java.awt.Component,%20java.lang.Object,%20java.lang.String,%20int,%20javax.swing.Icon,%20java.lang.Object[],%20java.lang.Object)))
