### PR TITLE
38&45: Change group buttons and fix bug.

### LINKED ISSUE #38: Change group buttons
Button doesn't feel intuitive.. I expect something to happen, but that not always the case..

maybe use radio-buttons or single-selects? or let the selected groupBtn stay selected until the sender-list changes..

wdyt?

### LINKED ISSUE #45: User not deleted from groups.
When a Chat window is closed, the user is removed from the Chat instance but not from his groups.

### PR DESCRIPTION
**Pull request by ingokuba**
Closes #38 
Closes #45

### CODE REVIEW

**Comment by ingokuba** [comment]
@thisIsTheFoxe Do you wanna review something too? :)

**Comment by ingokuba** [comment]
example
Very beautiful

**Comment by ingokuba** [comment]
https://codecov.io/gh/ingokuba/swing-chat/src/3833bc012e481c04833db28bb840cdf12f42b203/src/main/java/dhbw/swingchat/components/ToastMessage.java#L63...64
Not testing this kind of shit again for 0.5% coverage :roll_eyes:

File: src/main/java/dhbw/swingchat/components/ToastMessage.java [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+        panel.add(toastLabel);
+        setVisible(false);
+
+        new Thread() {
+
+            public void run()
+            {
+                try {
+                    Thread.sleep(miliseconds);
+                    dispose();
```
Comment (ingokuba) [inline src/main/java/dhbw/swingchat/components/ToastMessage.java]: Should this be in a `finally` block? so it will def be disposed? hmmmm

Comment (ingokuba) [reply src/main/java/dhbw/swingchat/components/ToastMessage.java]: Tried to test it, i don't know how :man_shrugging:

**Comment by thisIsTheFoxe** [comment]
looking good, some feature suggestions:
- clear the groups when a user edits the "receivers" (on the left)
- keep the currently selected group active when reloading. E.g. when I create a new group, all groups from all users get reset while receivers are the same. (Bug or intended?)

File: src/main/java/dhbw/swingchat/components/ToastMessage.java (hunk 1 above)
Comment (thisIsTheFoxe) [reply src/main/java/dhbw/swingchat/components/ToastMessage.java]: idk.. is that the easiest way to create a timeout in Java? It's at least quite readable which I think is real nice..

File: src/main/java/dhbw/swingchat/components/ToastMessage.java [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+
+    private static final long serialVersionUID = 1L;
+
+    private int               miliseconds;
+
+    /**
+     * Creates a toast message for a given time.
+     * 
+     * @param message The text to display.
+     * @param time The display duration of the message.
```
Comment (thisIsTheFoxe) [inline src/main/java/dhbw/swingchat/components/ToastMessage.java]: ..display duration of the message **in milliseconds**

File: src/main/java/dhbw/swingchat/components/ChatWindow.java [hunk 3]
```diff
@@ -175,9 +177,17 @@ private void updateGroups()
...
                             JCheckBox box = (JCheckBox)component;
-                            box.setSelected(group.contains(box.getText()));
+                            boolean inGroup = group.contains(box.getText());
+                            if (box.isSelected() != inGroup) {
+                                changed = true;
+                            }
+                            box.setSelected(inGroup);
+                        }
+                        if (!changed) {
+                            showToast("Nothing changed.", 1000);
```
Comment (thisIsTheFoxe) [inline src/main/java/dhbw/swingchat/components/ChatWindow.java]: Idk, tbh.. It might get annoying over time... especially with the *VERY INFORMATIVE* message "Nothing changed." 😐

File: src/main/java/dhbw/swingchat/components/ChatWindow.java [hunk 4]
```diff
@@ -175,9 +177,17 @@ private void updateGroups()
...
                         for (Component component : userPanel.getComponents()) {
                             JCheckBox box = (JCheckBox)component;
-                            box.setSelected(group.contains(box.getText()));
+                            boolean inGroup = group.contains(box.getText());
+                            if (box.isSelected() != inGroup) {
+                                changed = true;
+                            }
+                            box.setSelected(inGroup);
+                        }
+                        if (!changed) {
```
[the remark this answers is not in the document]
Comment (ingokuba) [reply src/main/java/dhbw/swingchat/components/ChatWindow.java]: I thought you wanted feedback when nothing happens :grin: I can also use a [ToggleButton](https://www.geeksforgeeks.org/java-swing-jtogglebutton-class/) - is that better?

File: src/main/java/dhbw/swingchat/components/ToastMessage.java (hunk 2 above)
Comment (ingokuba) [reply src/main/java/dhbw/swingchat/components/ToastMessage.java]: true! units are important

File: src/main/java/dhbw/swingchat/components/ChatWindow.java (hunk 3 above)
Comment (ingokuba) [reply src/main/java/dhbw/swingchat/components/ChatWindow.java]: haha I'm good with words

**Comment by ingokuba** [comment]
a lot of changes

File: src/test/java/dhbw/swingchat/components/ChatWindowIT.java [hunk 5]
```diff
@@ -164,7 +165,7 @@ public void should_not_create_group_with_null_name()
         assertThat(chat.getGroups(), hasSize(0));
 
         Assertions.assertThrows(WaitTimedOutError.class, () -> {
-            chatWindow.dialog();
+            WindowFinder.findDialog(Dialog.class).withTimeout(100).using(chatWindow.robot());
```
Comment (ingokuba) [inline src/test/java/dhbw/swingchat/components/ChatWindowIT.java]: Quicker :)

File: src/main/java/dhbw/swingchat/instance/Chat.java [hunk 6]
```diff
@@ -78,15 +78,15 @@ public Chat addGroup(Group group)
...
+        notifyObservers(ChangeEvent.add(group));
         return this;
     }
 
     public Chat removeGroup(Group group)
     {
         if (groups.remove(group)) {
             setChanged();
-            notifyObservers(ChangeMode.GROUP);
+            notifyObservers(ChangeEvent.remove(group));
```
Comment (thisIsTheFoxe) [inline src/main/java/dhbw/swingchat/instance/Chat.java]: very semantic and understandable! ^^ 👍

File: src/main/java/dhbw/swingchat/components/ChatWindow.java [hunk 7]
```diff
@@ -101,12 +108,27 @@ public void windowClosing(WindowEvent e)
...
+            private static final long serialVersionUID = 1L;
+
+            @Override
+            public void actionPerformed(ActionEvent e)
+            {
+                groupButtons.clearSelection();
+            }
         });
+        box.setName(name);
+        userPanel.add(box, "wrap");
```
[the remark this answers is not in the document]
Comment (ingokuba) [reply src/main/java/dhbw/swingchat/components/ChatWindow.java]: I have to set the text at the end or else it wont show :man_shrugging: try it - strange swing bug. something to to with redrawing and packing

File: src/main/java/dhbw/swingchat/components/ChatWindow.java [hunk 8]
```diff
@@ -277,22 +292,50 @@ private void message(String message)
...
+            Object eventObject = event.getObject();
+            if (eventObject instanceof String) {
+                messages.addElement((String)eventObject);
+            }
+            else if (eventObject instanceof User) {
                 userPanel.setVisible(false);
-                userPanel.removeAll();
-                updateUsers();
+                User eventUser = (User)eventObject;
+                if (event.getMode() == ADD) {
```
[the remark this answers is not in the document]
Comment (ingokuba) [reply src/main/java/dhbw/swingchat/components/ChatWindow.java]: I think so too. [KISS](https://en.wikipedia.org/wiki/KISS_principle) you know :wink: can be made abstract if needed

File: src/main/java/dhbw/swingchat/components/ChatWindow.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (thisIsTheFoxe) [reply src/main/java/dhbw/swingchat/components/ChatWindow.java]: oh.. that IS strange... whatevs.. thx

File: src/main/java/dhbw/swingchat/components/ChatWindow.java [hunk 9]
```diff
@@ -112,20 +121,32 @@ public void windowClosing(WindowEvent e)
...
+        box.setName(name);
+        userPanel.add(box, "wrap");
+        box.setText(name);
     }
 
     private void addChangeThemeButton()
     {
         JButton themeBtn = new JButton();
-        themeBtn.setOpaque(true);
-        themeBtn.setBorderPainted(false);
```
Comment (thisIsTheFoxe) [inline src/main/java/dhbw/swingchat/components/ChatWindow.java]: these are needed or else the background color won't change..

File: src/main/java/dhbw/swingchat/components/ChatWindow.java [hunk 10]
```diff
@@ -221,44 +242,33 @@ public Image getPNGImageNamed(String imageName)
...
 
-    private void updateMessageList()
+    private void addGroup(Group group)
     {
-        DefaultListModel<String> model = new DefaultListModel<>();
-        for (String message : user.getMessages()) {
-            model.addElement(message);
+        if (group.contains(user)) {
+            String groupName = group.getName();
+            JToggleButton groupButton = new JToggleButton();
```
Comment (thisIsTheFoxe) [inline src/main/java/dhbw/swingchat/components/ChatWindow.java]:
```
groupButton.setOpaque(true);
groupButton.setBorderPainted(false);
```
are needed or there will be wired UI bugs with the darkMode

Screenshot 2019-12-31 at 4 39 16 PM

File: src/main/java/dhbw/swingchat/components/ChatWindow.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (thisIsTheFoxe) [reply src/main/java/dhbw/swingchat/components/ChatWindow.java]: haven't heard about *KISS* yet.. luv it :D

File: src/main/java/dhbw/swingchat/instance/User.java [hunk 11]
```diff
@@ -40,12 +42,31 @@ public User message(String message)
...
+
+    @Override
+    public boolean equals(Object obj)
+    {
+        if (obj instanceof User) {
+            User user = (User)obj;
+            if (!getName().equals(user.getName())) {
+                return false;
+            }
+            return true;
```
Comment (thisIsTheFoxe) [inline src/main/java/dhbw/swingchat/instance/User.java]: looks strange.. check `if name.eq(u.getName())` and `return true`.. and have one `return false` at the end of the function if it continues to be executed (and the if's failed)

File: src/test/java/dhbw/swingchat/components/MainWindowIT.java [hunk 12]
```diff
@@ -164,4 +164,25 @@ public void should_delete_user_from_group()
...
+        // create user 2
+        mainWindow.textBox("username").enterText("testName2").pressAndReleaseKeys(VK_ENTER);
+        // create group with user 1&2
+        WindowFinder.findFrame("testName1").using(mainWindow.robot()).button("newGroup").click();
+        mainWindow.dialog().textBox().enterText("All").pressAndReleaseKeys(VK_ENTER);
+
+        // close window of user 1
+        WindowFinder.findFrame("testName1").using(mainWindow.robot()).close();
+
+        // group 'All' still exists
```
Comment (thisIsTheFoxe) [inline src/test/java/dhbw/swingchat/components/MainWindowIT.java]: nice comments ^^

File: src/test/java/dhbw/swingchat/instance/GroupTest.java [hunk 13]
```diff
@@ -101,7 +101,7 @@ public void should_remove_user()
         User user = new User("Hans");
         Group group = new Group("Test", user);
 
-        group.remove(user);
+        group.remove(new User("Hans"));
```
Comment (thisIsTheFoxe) [inline src/test/java/dhbw/swingchat/instance/GroupTest.java]: why this? also, is `user` unused now?

File: src/test/java/dhbw/swingchat/test/ThemedJFrameIT.java [hunk 14]
```diff
@@ -60,26 +65,28 @@ public void should_switch_mode(){
...
     @Test
-    public void should_update_frame(){
+    public void should_update_frame()
+    {
         populate_frame();
 
         assertDoesNotThrow(() -> frame.updateFrame());
     }
 }
-
```
Comment (thisIsTheFoxe) [inline src/test/java/dhbw/swingchat/test/ThemedJFrameIT.java]: could've done all that in a final "refactoring" issue.. but whatevs.. thank, ig.. ^-^

File: src/test/java/dhbw/swingchat/instance/GroupTest.java (hunk 13 above)
Comment (ingokuba) [reply src/test/java/dhbw/swingchat/instance/GroupTest.java]: Because they where compared by object id before. this scenario barely happens in real conditions

File: src/test/java/dhbw/swingchat/test/ThemedJFrameIT.java (hunk 14 above)
Comment (ingokuba) [reply src/test/java/dhbw/swingchat/test/ThemedJFrameIT.java]: Eigentlich ja

File: src/main/java/dhbw/swingchat/components/ChatWindow.java (hunk 10 above)
Comment (ingokuba) [reply src/main/java/dhbw/swingchat/components/ChatWindow.java]: How can I replicate this issue? it works for me :thinking:

File: src/main/java/dhbw/swingchat/instance/User.java (hunk 11 above)
Comment (ingokuba) [reply src/main/java/dhbw/swingchat/instance/User.java]: Yees, sonar already told me :D

File: src/test/java/dhbw/swingchat/components/MainWindowIT.java (hunk 12 above)
Comment (ingokuba) [reply src/test/java/dhbw/swingchat/components/MainWindowIT.java]: shush! it's a strange test to reach code cov :laughing:

**Comment by ingokuba** [comment]
fuck codecov

File: src/main/java/dhbw/swingchat/components/ChatWindow.java (hunk 10 above)
Comment (thisIsTheFoxe) [reply src/main/java/dhbw/swingchat/components/ChatWindow.java]: MacOS issue I guess.. as said it works with `setOpaque(true)` and `setBorderPainted(false)`

File: src/main/java/dhbw/swingchat/components/ChatWindow.java (hunk 9 above)
Comment (ingokuba) [reply src/main/java/dhbw/swingchat/components/ChatWindow.java]: da
looks strange on ubuntu :thinking:

Comment (ingokuba) [reply src/main/java/dhbw/swingchat/components/ChatWindow.java]: but ok, if it works better for :apple:

**Comment by ingokuba** [comment]
I abused my admin powers :smiling_imp:

File: src/main/java/dhbw/swingchat/components/ChatWindow.java (hunk 9 above)
Comment (thisIsTheFoxe) [reply src/main/java/dhbw/swingchat/components/ChatWindow.java]: ok a bit wired, but still readable.. open a new issue mby? .-.
